### ISSUE TITLE
Host header finding issue

### ISSUE THREAD

**Issue by 1995parham** [AUT-CEIT/UDPProxy#1]
The host header finding procedure has an issue. The issue is using `Host:` with `:` when slicing is done by `:` is invalid.

**Comment by parsaaes** [comment]
I think the `:` in `http://` is causing the problem in splitting.
Parsing like this should work:

```java
String[] parsedHeader = new String[2];
parsedHeader[0] = header.substring(0, header.indexOf(":"));
parsedHeader[1] = header.substring(header.indexOf(":") + 1).trim();
```
and in this line:                
https://github.com/AUT-CEIT/UDPProxy/blob/8235c18b2a07a5f5adfda34fbe938e215e808b3f/src/ir/ac/aut/ceit/udpproxy/proxy/Server.java#L55
`:` in `.equals("Host:")` should be removed.

**Comment by 1995parham** [comment]
Thanks, I tried to do the same thing and corrected the issue.
